### ISSUE TITLE
Cannot find module 'gm'

### ISSUE THREAD

**Issue by CuriousNewt** [BenjaminBrandmeier/angular2-image-gallery#80]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'gm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Marek\Desktop\bile-domky\node_modules\angular2-image-gallery\convert.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

happens after I try the convert code - apparently I am missing graphicsMagick? However, I got it installed and verified according to the GM installation guide. Tried in VSCode terminal and Win cmd

EDIT: might be an issue of ng8?

**Comment by CuriousNewt** [comment]
Solved - npm install gm --save
